# Generated by Django 3.0.2 on 2020-01-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Club Name')),
                ('country', models.CharField(max_length=50, verbose_name='Nation')),
                ('date_formed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=50, verbose_name='Nationality')),
                ('joined_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.Club', verbose_name='Current Club')),
            ],
        ),
    ]
